#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_home:
    path: /
    controller: App\Controller\HomeController::home
